### ISSUE TITLE
Show busy indicator while waiting for query results

### ISSUE THREAD

**Issue by kupietz** [KorAP/Kalamar#104]
Currently it's quite hard to tell if KorAP is busy or not.  A progress bar would be perfect, a large busy indicator would be great, but a local small indicator as for Corpus Statistics would already do the job.

**Comment by Akron** [comment]
As KorAP is (at least atm) no single page app, this indicator would start to run and will only stop once the page changes. Is that acceptable?

**Comment by kupietz** [comment]
> As KorAP is (at least atm) no single page app, this indicator would start to run and will only stop once the page changes. Is that acceptable?

Absolutely, I think this fulfill  the by far the most important function.
