### ISSUE TITLE
Add button to jump to random page

### ISSUE THREAD

**Issue by kupietz** [KorAP/Kalamar#141]
While we cannot sort query results (randomly): 

In order to get an overview over the variance of matches it would be nice to easily jump to a random results page.

Maybe by introducing a new button (probably using the fa-random symbol) in the page navigation in right bottom corner.

**Comment by Akron** [comment]
Like https://github.com/KorAP/Kalamar/issues/5 ?

**Comment by kupietz** [comment]
Yes, but in this context, even more helpful if you don't have to enter a random page yourself. And the concept of such buttons (usually rather check-button :/) is hopefully not too much abused.

**Comment by Akron** [comment]
I see. Maybe this is quite specific and could be made available as a plugin instead.

**Comment by kupietz** [comment]
> I see. Maybe this is quite specific and could be made available as a plugin instead.

It would indeed be very KorAP specific and also temporal (until results can be sorted). For that reason, I don't know, if this application is general enough to justify a plugin socket.

**Comment by Akron** [comment]
The major reason to make this a plugin I see is "temporal": When we make it a plugin and have a fairly stable API, users that rely on it (for whatever reason) can keep this functionality, while we don't have to support it in core. And I think only a few users will be interested, so another minor reason to make this a plugin. The good thing here is: The plugin can be a static js file with no server component required. https://github.com/KorAP/Kalamar/issues/5 could also be a plugin, though I think this is less specific and not temporal.
