### ISSUE TITLE
Show all metadata by one click on the reference

### ISSUE THREAD

**Issue by Akron** [KorAP/Kalamar#16]
Currently not all metadata fields are shown, although they may be part of a ```fields``` request.
For all texts, all metadata fields should be retrievable in a table view.
In addition, fields may be shown as a KWIC column, see #13 .

**Comment by margaretha** [comment]
> fields may be shown as a KWIC column, see #13 .

what do you mean with that?

**Comment by Akron** [comment]
Oh - yeah, that's misleading. I meant that you may want to add field info to the KWIC lines similar to the siglen. So a line may look like:
```[author][leftcontext *match* rightcontext]```

**Comment by margaretha** [comment]
> Currently not all metadata fields are shown, although they may be part of a VC.

This is a bit vague as well. I suppose there should be metadata info for each of the results.

**Comment by Akron** [comment]
You are right.

**Comment by Akron** [comment]
Metadata views are now available. The optional integration in KWICs will be discussed in the reopened issue #13 .
