### ISSUE TITLE
Long queries fail with »Parameter "q" invalid«

### ISSUE THREAD

**Issue by kupietz** [KorAP/Kalamar#169]
Long valid queries which work via the API, such as [this](https://korap.ids-mannheim.de/api/v1.0/search?q=%28%5borth%21%3d%22Kulturfilm%28s%29%3f%22%5d%20%7c%20%5borth%21%3d%22Mandy%22%5d%20%7c%20%5borth%21%3d%22Theaterst%c3%bcck%28s%29%3f%22%5d%20%7c%20%5borth%21%3d%22Funky%22%5d%20%7c%20%5borth%21%3d%22Schauspiel%28s%29%3f%22%5d%20%7c%20%5borth%21%3d%22Zadek%28s%29%3f%22%5d%20%7c%20%5borth%21%3d%22Sobol%28s%29%3f%22%5d%20%7c%20%5borth%21%3d%22%28T%7ct%29he%22%5d%20%7c%20%5borth%21%3d%22Electro%22%5d%20%7c%20%5borth%21%3d%22%28Holocaust%29%3f%28-%29%3f%28M%7cm%29usical%28s%29%3f%22%5d%20%7c%20%5borth%21%3d%22%28Holocaust%29%3f%28-%29%3f%28S%7cs%29t%c3%bcck%28s%29%3f%22%5d%20%7c%20%5borth%21%3d%22Kakadu%22%20%26%20orth%21%3d%22Global%22%5d%20%7c%20%5borth%21%3d%22Andrea%22%5d%20%7c%20%5borth%21%3d%22%28D%7cd%29%3fel%22%5d%20%7c%20%5borth%21%3d%22Little%22%5d%20%7c%20%5borth%21%3d%22Revue%22%5d%20%7c%20%5borth%21%3d%22Sarah%22%5d%20%7c%20%5borth%21%3d%22%28M%7cm%29y%22%5d%20%7c%20%5bcorenlp%2fp%21%3d%22FM%22%5d%20%7c%20%5bmarmot%2fp%21%3d%22FM%22%5d%20%7c%20%5bopennlp%2fp%21%3d%22FM%22%5d%20%7c%20%5btt%2fp%21%3d%22FM%22%5d%29%20%5borth%3d%22Ghetto%28s%29%3f%22%5d%20%28%5borth%21%3d%22Bells%22%5d%20%7c%20%5borth%21%3d%22Byke%22%5d%20%7c%20%5borth%21%3d%22Gospel%22%5d%20%7c%20%5borth%21%3d%22Sup%28a%7cer%29star%22%5d%20%7c%20%5borth%21%3d%22Fabulous%22%5d%20%7c%20%5borth%21%3d%22Schauspiel%22%5d%20%7c%20%5borth%21%3d%22Swingers%22%5d%20%7c%20%5borth%21%3d%22Art%22%5d%20%7c%20%5borth%21%3d%22Tech%22%5d%20%7c%20%5borth%21%3d%22Fly%22%5d%20%7c%20%5borth%21%3d%22Gazette%22%5d%20%7c%20%5borth%21%3d%22Soul%22%5d%20%7c%20%5borth%21%3d%22House%22%5d%20%7c%20%5borth%21%3d%22%28N%7cn%29ovo%22%5d%20%7c%20%5borth%21%3d%22Project%22%5d%20%7c%20%5borth%21%3d%22Kickers%22%5d%20%7c%20%5borth%21%3d%22Bitch%22%5d%20%7c%20%5borth%21%3d%22Brother%28s%29%3f%22%5d%20%7c%20%5borth%21%3d%22People%22%5d%20%7c%20%5borth%21%3d%22Philosophy%22%5d%20%7c%20%5borth%21%3d%22Dictionary%22%5d%20%7c%20%5borth%21%3d%22Ruff%22%5d%20%7c%20%5borth%21%3d%22Rap%22%5d%20%7c%20%5borth%21%3d%22Children%22%5d%20%7c%20%5borth%21%3d%22Elektro%22%5d%20%7c%20%5borth%21%3d%22Dance%22%5d%20%7c%20%5borth%21%3d%22Song%22%5d%20%7c%20%5borth%21%3d%22Metal%22%5d%20%7c%20%5borth%21%3d%22Bass%22%5d%20%5bcorenlp%2fp%21%3d%22FM%22%5d%20%7c%20%5bmarmot%2fp%21%3d%22FM%22%5d%20%7c%20%5bopennlp%2fp%21%3d%22FM%22%5d%20%7c%20%5btt%2fp%21%3d%22FM%22%5d%29&cq=textType%20%3d%20%2fZeit.%2a%2f%20%26%20pubDate%20in%202019&ql=poliqarp&fields=corpusSigle,textSigle,pubDate,pubPlace,availability,textClass&access-rewrite-disabled=true) fail in the web UI as shown [here](https://korap.ids-mannheim.de/?q=%28%5borth%21%3d%22Kulturfilm%28s%29%3f%22%5d%20%7c%20%5borth%21%3d%22Mandy%22%5d%20%7c%20%5borth%21%3d%22Theaterst%c3%bcck%28s%29%3f%22%5d%20%7c%20%5borth%21%3d%22Funky%22%5d%20%7c%20%5borth%21%3d%22Schauspiel%28s%29%3f%22%5d%20%7c%20%5borth%21%3d%22Zadek%28s%29%3f%22%5d%20%7c%20%5borth%21%3d%22Sobol%28s%29%3f%22%5d%20%7c%20%5borth%21%3d%22%28T%7ct%29he%22%5d%20%7c%20%5borth%21%3d%22Electro%22%5d%20%7c%20%5borth%21%3d%22%28Holocaust%29%3f%28-%29%3f%28M%7cm%29usical%28s%29%3f%22%5d%20%7c%20%5borth%21%3d%22%28Holocaust%29%3f%28-%29%3f%28S%7cs%29t%c3%bcck%28s%29%3f%22%5d%20%7c%20%5borth%21%3d%22Kakadu%22%20%26%20orth%21%3d%22Global%22%5d%20%7c%20%5borth%21%3d%22Andrea%22%5d%20%7c%20%5borth%21%3d%22%28D%7cd%29%3fel%22%5d%20%7c%20%5borth%21%3d%22Little%22%5d%20%7c%20%5borth%21%3d%22Revue%22%5d%20%7c%20%5borth%21%3d%22Sarah%22%5d%20%7c%20%5borth%21%3d%22%28M%7cm%29y%22%5d%20%7c%20%5bcorenlp%2fp%21%3d%22FM%22%5d%20%7c%20%5bmarmot%2fp%21%3d%22FM%22%5d%20%7c%20%5bopennlp%2fp%21%3d%22FM%22%5d%20%7c%20%5btt%2fp%21%3d%22FM%22%5d%29%20%5borth%3d%22Ghetto%28s%29%3f%22%5d%20%28%5borth%21%3d%22Bells%22%5d%20%7c%20%5borth%21%3d%22Byke%22%5d%20%7c%20%5borth%21%3d%22Gospel%22%5d%20%7c%20%5borth%21%3d%22Sup%28a%7cer%29star%22%5d%20%7c%20%5borth%21%3d%22Fabulous%22%5d%20%7c%20%5borth%21%3d%22Schauspiel%22%5d%20%7c%20%5borth%21%3d%22Swingers%22%5d%20%7c%20%5borth%21%3d%22Art%22%5d%20%7c%20%5borth%21%3d%22Tech%22%5d%20%7c%20%5borth%21%3d%22Fly%22%5d%20%7c%20%5borth%21%3d%22Gazette%22%5d%20%7c%20%5borth%21%3d%22Soul%22%5d%20%7c%20%5borth%21%3d%22House%22%5d%20%7c%20%5borth%21%3d%22%28N%7cn%29ovo%22%5d%20%7c%20%5borth%21%3d%22Project%22%5d%20%7c%20%5borth%21%3d%22Kickers%22%5d%20%7c%20%5borth%21%3d%22Bitch%22%5d%20%7c%20%5borth%21%3d%22Brother%28s%29%3f%22%5d%20%7c%20%5borth%21%3d%22People%22%5d%20%7c%20%5borth%21%3d%22Philosophy%22%5d%20%7c%20%5borth%21%3d%22Dictionary%22%5d%20%7c%20%5borth%21%3d%22Ruff%22%5d%20%7c%20%5borth%21%3d%22Rap%22%5d%20%7c%20%5borth%21%3d%22Children%22%5d%20%7c%20%5borth%21%3d%22Elektro%22%5d%20%7c%20%5borth%21%3d%22Dance%22%5d%20%7c%20%5borth%21%3d%22Song%22%5d%20%7c%20%5borth%21%3d%22Metal%22%5d%20%7c%20%5borth%21%3d%22Bass%22%5d%20%5bcorenlp%2fp%21%3d%22FM%22%5d%20%7c%20%5bmarmot%2fp%21%3d%22FM%22%5d%20%7c%20%5bopennlp%2fp%21%3d%22FM%22%5d%20%7c%20%5btt%2fp%21%3d%22FM%22%5d%29&cq=textType%20%3d%20%2fZeit.%2a%2f%20%26%20pubDate%20in%202019&ql=poliqarp).

**Comment by Akron** [comment]
Ah - I see. I guess we limit it to 1000 because of Browser support. I am not sure about the current situation, but there are different limits for different browsers, that are not defined per se for URLs. But if we want to support copy'n'paste between different browsers for Queries (and I think the problem was Edge), we should limit the supported characters to the lowest supported amount. Maybe a solution would be to limit the query parameter for the API as well, while this still leaves problems for long `cq`-parameters.

**Comment by Akron** [comment]
Alternatively we may be able to check the browser limits and give meaningful error messages for these.

**Comment by kupietz** [comment]
I think we should increase the limit to about 4096 and provide a better error message in addition, see: https://korap.ids-mannheim.de/gerrit/c/KorAP/Kalamar/+/5897

Edge doesn't matter much in comparison, I think.

**Comment by kupietz** [comment]
Yes, let's rather use the limit of the API. I just couldn't figure it out in time. 4096 is just as arbitrary as 1000 (also unrelated to Edge), but will avoid the problem in almost all cases, for the Rechtschreibrat. It's not like with vc definitions that can often get much larger. Queries can get big for excluding false positives, but not much bigger. There is no reason to limit them to 1000 characters. (Edge users will be used to trouble and probably get a good error message :)

**Comment by kupietz** [comment]
Maybe 4096 is a good compromise in our case: https://stackoverflow.com/questions/812925/what-is-the-maximum-possible-length-of-a-query-string
