### ISSUE TITLE
Virtual Corpus info

### ISSUE THREAD

**Issue by margaretha** [KorAP/Kalamar#17]
Virtual corpus size should be shown both for private Virtual corpora in a user page and when specified together with a search query. Other info regarding the VC such as the document titles, dates, etc should be available as well. In Cosmas 2, such info can be exported.

Has there been an open issue regarding corpus browsing already?

**Comment by Akron** [comment]
There is no issue for corpus browsing, so I guess this should be opened.

**Comment by hebasta** [comment]
Maybe there should actually be two issues, one regarding the statistical information of virtual corpora (number of documents, tokens, sentences, paragraphs, ...) and one regarding the "Korpuspräsentationen" of Cosmas II which can contain statistical information, too.

**Comment by Akron** [comment]
I think, this issue can be closed now.

**Comment by hebasta** [comment]
Issue closed, replaced by #25 and #26.
