### ISSUE TITLE
Put content and  news / changes ticker into a column

### ISSUE THREAD

**Issue by kupietz** [KorAP/Kalamar#174]
News in the central position is unusual and might be too prominent. This would go well hand in hand with #118 and #129.

Requested by Andreas.

**Comment by Akron** [comment]
We may want to have a UI meeting discussing the design of the landing page.

**Comment by Akron** [comment]
An additional prominent element for the start page may be also a request for citations in case the corpus is used.

**Comment by hebasta** [comment]
As discussed in the UI-Meeting it would make sense to display at the main landing page two columns, a larger "content" column(left side) and a slim news column. The news column should contain news(here general news and high prioritized news like downtime news have to be distinguished) and technical changes.

The content column should contain:
-  information about KorAP
-  corpora (link to DeReKo-release)
-  guided tour 
-  request for citations
(maybe displayed as tiles?)

**Comment by Akron** [comment]
I guess now that the news are removed, this issue can be closed, right?

**Comment by kupietz** [comment]
Now on a separate page.
