### ISSUE TITLE
Annotation Cheatsheet

### ISSUE THREAD

**Issue by margaretha** [KorAP/Kalamar#18]
Annotation cheatsheet lists all tags for each foundry and layers. It is identical to the annotation helper tool, but in form of a table. While the annotation helper tool is useful for writing query, the cheatsheet is useful when users need to look up for the meaning/description of some annotations, e.g. while analysing the results.

**CoreNLP**

| Layers        | Tags           | Description  |
| --------------- |:--------------:| ------------------|
| Lemma      |AA                | Superlative phrase with "am" |
|                   | AP                |   Adjective phrase |
| Named entity| I-LOC      |    Location |

It should be separate pages (not in the query results) in the help/tutorial. 
Since it contains the same content as the annotation helper, it should be able to be updated automatically, shouldn't it?

An alternative to the cheatsheet tables could be tooltips activated by mouse hovering over the annotation tags in a match info table view and a visualization/tree view.

**Comment by Akron** [comment]
I think, tooltips would be a reasonable thing.

**Comment by Akron** [comment]
I commited https://github.com/KorAP/Kalamar/commit/cc83bbc4f7c2f7000bd65cd1bdd2802bb3b25de2 , which adds tooltips to annotations in the annotation table. Currently it is limited to single-field values. Additions to the tree annotations should be straight forward.

**Comment by margaretha** [comment]
alright, thanks!
