### ISSUE TITLE
Terser fails in Docker

### ISSUE THREAD

**Issue by Akron** [KorAP/Kalamar#182]
Somehow the assets can't be build in Docker atm because Terser fails.

**Comment by kupietz** [comment]
The grunt-terser plugin requires Grunt `^1.x` ( see: https://www.npmjs.com/package/grunt-terser )

Reverting a34e6ae428f56d19252f6322257277e1f27e7799 would resolve the issue.

**Comment by Akron** [comment]
We are currently using Grunt `1.0.4`. The problem seems to be that the terser plugin no longer declares terser a dependency.
