### ISSUE TITLE
"Some fields are invalid" error 

### ISSUE THREAD

**Issue by hebasta** [KorAP/Kalamar#183]
Error "some fields are invalid" occurs: 1) clicking "grant access" or "abort" in the grant form 2) clicking at OAuth menu.

**Comment by Akron** [comment]
This occurs probably when no server side redirect is stored. A more correct handling of the redirect uris will hopefully solve that issue (prepared in Gerrit).

**Comment by Akron** [comment]
@hebasta Can you check if this is still a problem?

**Comment by hebasta** [comment]
Is resolved!
