### ISSUE TITLE
Handling unknown authorization scope

### ISSUE THREAD

**Issue by margaretha** [KorAP/Kalamar#191]
Kalamar should disallow asking for unknown authorization scope

![image](https://user-images.githubusercontent.com/5528620/215783398-519185a1-5c0e-4d24-a60e-707690a0240d.png)

example request:

`https://korap.ids-mannheim.de/instance/test/settings/oauth/authorize?client_id=clientId&redirect_uri=redirect_uri&response_type=code&state=ZMwDGTZ2RY&scope=unknown`

**Comment by Akron** [comment]
I think the handling needs to be done in the backend. However, if we want to have a second step of access granting, where Kalamar reports, which scope are accepted and how the final redirect looks like, that should be doable in Kalamar. Having a separate background checking step or keeping a list of valid scopes in the frontend seems to be unnecessary to me.

**Comment by Akron** [comment]
For me, that's a *wontfix*.
