### ISSUE TITLE
"Not authenticated" appears with "Scope required" error

### ISSUE THREAD

**Issue by margaretha** [KorAP/Kalamar#192]
When sending an authorization request without scope, Kalamar throws "not authenticated" error.

Example request:

`https://korap.ids-mannheim.de/instance/test/settings/oauth/authorize?client_id=client_id&redirect_uri=redirect_urit&response_type=code&state=ZMwDGTZ2RY`

![image](https://user-images.githubusercontent.com/5528620/215784741-b81b1e1e-f187-4b0a-88ba-cc0bc18a9670.png)

**Comment by Akron** [comment]
Only when the user is not authenticated ... right?

**Comment by Akron** [comment]
We discussed this topic in Slack. I don't think the user should be encouraged to log in, when a wrong and potentially malicious authorization request is done. To avoid this error message, the user should be lead to the start page, in case it is not logged in. When logged in, the settings page is fine and may help to check already granted authorizations.
