### ISSUE TITLE
Support VC sharing by link

### ISSUE THREAD

**Issue by Akron** [KorAP/Kalamar#207]
This was proposed by @kupietz via Slack. There was a complaint, that sharing a VC via link is not well supported.

To improve this situation, I would think at least two improvements need to be implemented:
1. Instead of an error message, when the user searches without a query, just politely welcome the user to type in a query.
2. The VC builder should have a way to either copy a link or open a new tab for a non-query window, so the generated link can easily be shared.

**Comment by kupietz** [comment]
On missing or empty query and non-empty vc parameter, the intro page with an initialized (maybe ideally expanded) corpus composition should be shown:

![image](https://github.com/user-attachments/assets/4b24c1be-23e8-4757-9195-de52313796b1)
