### ISSUE TITLE
Inconsistency between shown frequencies and number of kwic lines displayed, from R client to web gui, but also inside web gui

### ISSUE THREAD

**Issue by perkuhn** [KorAP/Kalamar#218]
following KorAP query:

https://korap.ids-mannheim.de/?q=%5borth%3dpopulistisches%5d&cq=availability%21%3dQAO-NC-LOC%3aids%20%26%20corpusSigle%20%3d%20%2fSOL%7c%5bSUTZ%5d%5b0-9%5d%5b0-9%5d%2f%20%26%20pubDate%20in%201975&ql=poliqarp

generated by the R-client (while working at home via vpn), yields a value (10) that is also displayed in the chart, URL taken from clickable data point. KorAP web gui shows also this value, but instead of kwic lines shows comment that there no results at all (in  other cases shows only fewer lines than value indicates).

... another example:

https://korap.ids-mannheim.de/?q=%5borth%3dpopulistisches%5d&cq=availability%21%3dQAO-NC-LOC%3aids%20%26%20corpusSigle%20%3d%20%2fSOL%7c%5bSUTZ%5d%5b0-9%5d%5b0-9%5d%2f%20%26%20pubDate%20in%202017&ql=poliqarp

client works with 108 hits, KorAP web gui also shows this frequency 108, but displays only 9 KWIC lines (offers five more pages to show kwics, but without content, only "no results" messages).

Starting the query inside KorAP gui with the same setting (query and vc) yields 9 hits and 9 kwic lines.

But: If you remove the licence restrictions (that should have no effect with this vc definition) and start again a query in the KorAP gui, you get the same effect as above: claiming 108 hits, displaying 9 kwic lines ... 

presumably the smaller numbers inside KorAP web gui (and thus the number of kwic lines) are correct, so the wrong results might be calculated from another vc and/or by ignoring the licence restrictions for the shown number but not ignoring this for displaying the kwics?

**Comment by Akron** [comment]
It was identified as probably a caching issue in Kalamar.

**Comment by perkuhn** [comment]
working without caching seems to solve problem inside web gui, RKorAP client script call of freqencyQuery still offers wrong numbers, e.g.

library(RKorAPClient)

startYear <- 1962
endYear <- 2023

query=c("[tt/l=populistisch]",
        "[orth=populistisch]", 
        "[orth=populistischer]", 
        "[orth=populistisches]")

ql="poliqarp"
vc = "availability!=QAO-NC-LOC:ids & corpusSigle = /SOL|[UTSZ][0-9][0-9]/ & pubDate in "
year <- c(startYear:endYear)
kco1 <- new("KorAPConnection", accessToken=NULL, verbose = T)

df <- frequencyQuery(kco1, query=query, vc=paste0(vc,year), expand=TRUE, ql=ql)
hc <- hc_freq_by_year_ci(df)
print(hc)

---->
...
Searching "[orth=populistisches]" in "availability!=QAO-NC-LOC:ids & corpusSigle = /SOL|[UTSZ][0-9][0-9]/ & pubDate in 1988": 23 hits, took 3.155619155 s

actually should be 0 hits

**Comment by Akron** [comment]
We expect the problem to be associated with https://github.com/KorAP/Kalamar/issues/219 .

**Comment by margaretha** [comment]
I have investigated the problem and managed to reproduce it. It seems to be a problem with the cache in Kustvakt. I will investigate further and fix it.

**Comment by margaretha** [comment]
I have made a fix in Kustvakt and it has already been run on the test instance.

**Comment by Akron** [comment]
Thank you very much - to be closed, when @perkuhn confirms the fix, #219 is still open for discussions.

**Comment by Akron** [comment]
@perkuhn Is that fixed?
