### ISSUE TITLE
Plugin: Tooltip-text is taken as the button label

### ISSUE THREAD

**Issue by Bodmo** [KorAP/Kalamar#224]
When adding a Plugin as a toggle button to the query panel, the 'title' property of the plugin is taken for the label of the button. Instead, I suppose that the 'name' property should be taken.

![Screenshot 2024-10-25 at 18-51-10 KorAP Finde »Kirchturm beim« mit Cosmas II](https://github.com/user-attachments/assets/bdc8518c-1e50-4b25-b4f9-0ff8385ea346)

**Comment by Bodmo** [comment]
Yes, exactly,  I thirst thought 'title' is taken from HTML.
For the moment, we have only 1 property for 2 purposes: a. a very short button label, and b. a longer description for the tooltip. 
'desc' is also a property of the plugin. 
So in some way a new property is needed for the label.

**Comment by Akron** [comment]
Yes, I think that's possible.

**Comment by Akron** [comment]
I added `desc` support for widgets in Gerrit.
