### ISSUE TITLE
Plugin: avoiding the plugins being moved down the page

### ISSUE THREAD

**Issue by Bodmo** [KorAP/Kalamar#226]
When a Widget plugin in the query panel is opened, the bar with the query plugins are moved to the bottom of the displayed plugin. See the red cicle in the screenshot:

![Screenshot GlemmAssist in both panels 2](https://github.com/user-attachments/assets/e2a74698-6f7e-4167-adc1-edfb44d7d041)

**Comment by Akron** [comment]
That's intended. What would you think to be a better behaviour?

**Comment by Akron** [comment]
These buttons allow to embed multiple widgets, so it's better they stay, where the new widgets occur in my opinion, just like with the different annotation views.
