### ISSUE TITLE
Statistical information of virtual corpora

### ISSUE THREAD

**Issue by hebasta** [KorAP/Kalamar#25]
Display of statistical information of virtual corpora (number of documents, texts, tokens, sentences)

**Comment by Akron** [comment]
I think we should discuss, where and when this information in the UI is positioned.

![vc-view-2018-02-15-nr](https://user-images.githubusercontent.com/506957/36259484-a020689a-125e-11e8-8c53-2f0f52c6864f.png)

I would argue that this information should only be available in case the corpus builder view is open.
I would also argue, that the information isn't visible by default but requires a user request, e.g. by clicking on a button ```statistics```. The button may be below the virtual corpus (2) or on its right (3).
When the information is loaded, it may appear either below (2) or on the right (3) of the VC.

It's important to keep in mind, that the VC can be arbitrarily wide, so it may be problematic to put the statistics information always on the right (3). This is especially true for small screens, e.g. on mobile devices.

We also need to address the requirement of further information regarding the corpus builder view, e.g. the loading, saving and sharing of VCs (I expect @margaretha will open an issue in regards to that soon).

We also may want to have a resemblance (i.e. the same design language) with the new match view, where all information and all buttons are below the snippet.

**Comment by Akron** [comment]
Already in master.
