### ISSUE TITLE
Formatting date

### ISSUE THREAD

**Issue by margaretha** [KorAP/Kalamar#33]
Fields with date value such as creationDate and pubDate should be formatted to a more readable text.

**Comment by Akron** [comment]
This will temporarily rely on field names having a "Date" ending, as the index currently does not differ between dates and numeric values.

**Comment by Akron** [comment]
After reviewing the problem, this is more appropriate to be resolved in KorAP/Krill.

**Comment by Akron** [comment]
Fixed in https://github.com/KorAP/Krill/commit/0c8a5c546d9d0c60911293eeca48455ef6fd6090
