### ISSUE TITLE
User-settings

### ISSUE THREAD

**Issue by hebasta** [KorAP/Kalamar#41]
The user should be able to choose certain settings to make the search in KorAP more comfortable

- choose metadata field names, the user is interested in and their order (see also #40). (All metadata field are displayed after clicking at a "more" button)

- ...

**Comment by Akron** [comment]
I think this issue should be moved to Kustvakt.

**Comment by margaretha** [comment]
Moved to https://github.com/KorAP/Kustvakt/issues/18
