### ISSUE TITLE
"no permission to access /kalamar on this server"

### ISSUE THREAD

**Issue by bansp** [KorAP/Kalamar#6]
Reposting Pavel Stranak's [message from the blog](http://korap.ids-mannheim.de/2015/06/kalamar/): 

>   Hi guys,
>   I would really like to try Kalamar, but I am getting “Forbidden. You don’t have permission to access 
>   /kalamar on this server.”
>   Pavel

@Pavel: Thanks for the note. Would you please say _how_ you attempted the connection?

It makes a bit of a difference whether you install with admin priviledges or not; in the latter case, you have to follow the installation messages a bit more closely to make sure that all the dependencies are met, so my .bashrc has the following two lines now:

> #added at the request of perlbrew
> source ~/perl5/perlbrew/etc/bashrc
> 
> #added at the request of cpanm
> cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)

I run it by doing `Kalamar$ morbo script/kalamar` and it's there, on http://localhost:3000/ .

**Comment by Akron** [comment]
I think it's a restriction problem. The post is now edited in the blog.
