### ISSUE TITLE
Fix operator choice in virtual collection window

### ISSUE THREAD

**Issue by EleFri** [KorAP/Kalamar#71]
"contains" wir einmal angeboten, ein anderes mal nicht. Wahrscheinlich ist es so gedacht, dass es für RE nicht angeboten werden soll, was logisch wäre. Wenn man aber RE wieder ausschaltet, erscheint "contains" nicht automatisch in der Auswahl wieder. Erst nachdem man auf ein anderes Key, z.B. corpusSigle statt corpusTitle klickt.

**Comment by Akron** [comment]
Thank you for filing this issue. Can you report all steps necessary to reproduce the problem?

**Comment by Akron** [comment]
Please add some information so this bug can be reproduced, otherwise we will close it.
