### ISSUE TITLE
OAuth2 client management

### ISSUE THREAD

**Issue by margaretha** [KorAP/Kalamar#80]
Kalamar should provide a user interface for OAuth2 client management presenting client info and enabling clients to reset their secrets and deregister themselves.

See
* https://github.com/KorAP/Kustvakt/wiki/Service:-OAuth2-Client-Secret-Reset
* https://github.com/KorAP/Kustvakt/wiki/Service:-OAuth2-Client-Deregistration

**Comment by Akron** [comment]
Deregistration implemented in https://github.com/KorAP/Kalamar/commit/1a9d5be919f870e30f05adea3d9285f237648711

**Comment by Akron** [comment]
Secret reset won't be implemented as part of Kalamar. It doesn't affect public clients at all and it would require client owners to submit their client secrets via a form for confidential clients, which is a bad design.
